### ISSUE TITLE
crash shortly after loading

### ISSUE THREAD

**Issue by sa13103** [asiekierka/UnlimitedChiselWorks-Botany#2]
ive been attempting to figure out how to recreat it but it seems to be just random for me.

here is a copy of the crash report.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Plugin (NotEnoughIDs-1.5.4.3.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.1.0.3.jar)
  DCLoadingPlugin (DummyCoreUnofficial-2.4.112.5.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.4-core.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  SmoothWaterCore (SmoothWater-0.1.4.jar)
  AstralCore (astralsorcery-1.12.2-1.10.11.jar)
  Wizardry Plugin (wizardry-0.9.9.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  Botania Tweaks Core (botaniatweaks-1.8.4.jar)
  FarseekCoreMod (Farseek-1.12-2.3.1.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
  LoadingPlugin (Quark-r1.5-145.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  llibrary (llibrary-core-1.0.10-1.12.2.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  HCASM (HammerCore-1.12.2-2.0.4.2.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.1.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  DLFMLCorePlugin (DynamicLights-1.12.2.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 2/19/19 1:28 AM
Description: Unexpected error

java.lang.NoClassDefFoundError: team/chisel/api/IChiselItem
	at pl.asie.ucw.UnlimitedChiselWorksBotany.onPlayerInteract(UnlimitedChiselWorksBotany.java:168)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2303_UnlimitedChiselWorksBotany_onPlayerInteract_LeftClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1116)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:232)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2249)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: team.chisel.api.IChiselItem
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at pl.asie.ucw.UnlimitedChiselWorksBotany.onPlayerInteract(UnlimitedChiselWorksBotany.java:168)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2303_UnlimitedChiselWorksBotany_onPlayerInteract_LeftClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1116)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:232)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2249)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['sa13103'/31116, l='MpServer', x=-199.72, y=70.00, z=301.02]]
	Chunk stats: MultiplayerChunkCache: 420, 420
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-202,64,256), Chunk: (at 6,4,0 in -13,16; contains blocks -208,0,256 to -193,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3130 game time, 3130 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 216 total; [EntityItemLoot['item.item.animania_raw_frog_legs'/34864, l='MpServer', x=-162.38, y=67.00, z=275.88], EntityTroll['Troll'/36928, l='MpServer', x=-166.02, y=32.00, z=308.98], EntityItemLoot['item.item.feather'/34880, l='MpServer', x=-152.17, y=73.00, z=357.35], EntityItemLoot['item.item.string'/34902, l='MpServer', x=-164.13, y=25.00, z=258.13], EntityItemLoot['item.tile.mushroom11'/34953, l='MpServer', x=-156.32, y=28.00, z=256.57], EntityItemLoot['item.tile.doublePlant.paeonia'/34958, l='MpServer', x=-142.82, y=69.00, z=271.78], MoCEntityAnchovy['Anchovy'/34961, l='MpServer', x=-167.36, y=61.01, z=364.95], MoCEntityAnchovy['Anchovy'/34962, l='MpServer', x=-169.50, y=61.82, z=367.50], MoCEntityAnchovy['Anchovy'/34963, l='MpServer', x=-170.50, y=62.05, z=370.50], MoCEntityAnchovy['Anchovy'/34964, l='MpServer', x=-171.50, y=60.72, z=369.50], EntityZombie['Zombie'/39110, l='MpServer', x=-149.50, y=82.00, z=301.50], EntityItemLoot['item.item.plants2.amaranthus_h_seeds'/39148, l='MpServer', x=-192.88, y=68.00, z=273.56], EntityTroll['Troll'/35103, l='MpServer', x=-169.50, y=28.00, z=298.50], EntityItemLoot['item.tile.block_cff_flowersc.redclover'/35106, l='MpServer', x=-154.13, y=71.00, z=249.16], MoCEntityJellyFish['JellyFish'/35109, l='MpServer', x=-179.50, y=61.83, z=346.50], MoCEntityJellyFish['JellyFish'/35110, l='MpServer', x=-175.50, y=61.01, z=349.50], MoCEntityAngler['Angler'/35111, l='MpServer', x=-184.92, y=61.97, z=341.00], MoCEntityAngler['Angler'/35112, l='MpServer', x=-179.85, y=61.03, z=352.15], EntitySkeleton['Skeleton'/39247, l='MpServer', x=-185.50, y=14.00, z=349.50], MoCEntityRoach['Roach'/35210, l='MpServer', x=-201.43, y=67.00, z=239.54], MoCEntityAngelFish['AngelFish'/35220, l='MpServer', x=-251.50, y=62.44, z=345.50], MoCEntityAngelFish['AngelFish'/35221, l='MpServer', x=-248.50, y=62.06, z=345.50], MoCEntityPiranha['Piranha'/35222, l='MpServer', x=-249.50, y=61.51, z=347.50], EntityItemLoot['item.item.feather'/39327, l='MpServer', x=-163.27, y=77.00, z=336.56], EntityZombie['Zombie'/39333, l='MpServer', x=-172.50, y=19.00, z=365.50], EntityAncientGolem['Ancient Golem'/37305, l='MpServer', x=-166.50, y=20.00, z=299.50], EntityItemLoot['item.item.animania_raw_frog_legs'/37344, l='MpServer', x=-158.34, y=78.00, z=336.13], EntityItemLoot['item.tile.mushroom'/35316, l='MpServer', x=-163.05, y=21.00, z=291.11], EntityItemLoot['item.item.iceandfire.troll_tusk'/35317, l='MpServer', x=-162.79, y=21.00, z=290.51], EntityItemLoot['item.item.iceandfire.troll_leather_forest'/35318, l='MpServer', x=-163.13, y=21.00, z=291.04], EntityItemLoot['item.item.iceandfire.troll_leather_forest'/35323, l='MpServer', x=-168.15, y=11.00, z=259.86], EntityItemLoot['item.tile.mushroom'/35324, l='MpServer', x=-168.60, y=11.00, z=259.44], EntityCreeper['Creeper'/39444, l='MpServer', x=-161.84, y=19.00, z=323.50], EntityItemLoot['item.item.iceandfire.troll_leather_mountain'/35359, l='MpServer', x=-158.75, y=27.00, z=309.43], EntityItemLoot['item.tile.mushroom'/37420, l='MpServer', x=-200.36, y=37.00, z=320.65], EntityItemLoot['item.tile.mushroom'/37421, l='MpServer', x=-201.41, y=36.91, z=323.17], EntityItemLoot['item.tile.mushroom1'/37427, l='MpServer', x=-176.88, y=15.00, z=332.68], EntityItemLoot['item.item.iceandfire.troll_weapon.hammer'/37429, l='MpServer', x=-200.85, y=36.85, z=321.48], EntityItemLoot['item.item.bone'/35390, l='MpServer', x=-162.59, y=21.00, z=291.07], EntityItemLoot['item.tile.stonebrick'/35392, l='MpServer', x=-162.58, y=21.00, z=290.34], EntityItemLoot['item.item.bone'/35394, l='MpServer', x=-168.88, y=11.00, z=259.19], EntityItemLoot['item.tile.stonebrick'/35396, l='MpServer', x=-168.88, y=11.00, z=259.47], EntityItemLoot['item.item.iceandfire.troll_leather_forest'/35402, l='MpServer', x=-153.49, y=26.00, z=348.88], EntityItemLoot['item.tile.mushroom'/35403, l='MpServer', x=-153.18, y=25.00, z=351.55], EntityDweller['Dweller'/39506, l='MpServer', x=-171.50, y=19.00, z=308.50], EntitySkeleton['Skeleton'/39509, l='MpServer', x=-161.50, y=17.00, z=363.50], EntitySkeleton['Skeleton'/39538, l='MpServer', x=-252.78, y=16.00, z=231.70], EntityPlayerSP['sa13103'/31116, l='MpServer', x=-199.72, y=70.00, z=301.02], EntityLatchedRenderer['unknown'/31358, l='MpServer', x=8.50, y=65.00, z=8.50], EntitySkeleton['Skeleton'/37530, l='MpServer', x=-267.50, y=12.00, z=255.50], EntityTroll['Troll'/39586, l='MpServer', x=-178.50, y=21.00, z=340.50], EntityItemLoot['item.item.iceandfire.troll_weapon.hammer'/35492, l='MpServer', x=-159.26, y=27.00, z=308.58], EntityItemLoot['item.item.string'/39590, l='MpServer', x=-201.13, y=13.00, z=343.86], MoCEntityRaccoon['Raccoon'/29353, l='MpServer', x=-267.50, y=72.00, z=221.50], MoCEntityPandaBear['PandaBear'/29362, l='MpServer', x=-274.50, y=73.00, z=224.50], MoCEntityBunny['Bunny'/29364, l='MpServer', x=-273.50, y=71.00, z=256.50], MoCEntityBunny['Bunny'/29365, l='MpServer', x=-275.50, y=75.00, z=259.50], EntityItemLoot['item.item.string'/37559, l='MpServer', x=-172.64, y=21.00, z=306.84], EntityItemLoot['item.tile.log.oak'/35518, l='MpServer', x=-154.60, y=25.00, z=348.95], EntityZombie['Zombie'/39628, l='MpServer', x=-222.50, y=54.00, z=347.50], EntityItemLoot['item.item.iceandfire.troll_tusk'/39632, l='MpServer', x=-171.72, y=20.00, z=271.51], EntityItemLoot['item.item.iceandfire.troll_leather_forest'/39633, l='MpServer', x=-171.66, y=20.00, z=271.88], EntityZombie['Zombie'/39648, l='MpServer', x=-147.50, y=29.00, z=360.50], EntityItemLoot['item.item.iceandfire.troll_weapon.trunk'/39651, l='MpServer', x=-170.61, y=20.00, z=271.50], MoCEntityWraith['Wraith'/39652, l='MpServer', x=-136.12, y=90.83, z=324.90], EntityAshen['Ashen'/39659, l='MpServer', x=-217.50, y=14.00, z=358.50], EntitySpider['Spider'/39695, l='MpServer', x=-203.03, y=17.00, z=355.01], MoCEntitySnail['Snail'/35613, l='MpServer', x=-148.50, y=98.00, z=316.50], MoCEntitySnail['Snail'/35614, l='MpServer', x=-150.50, y=98.00, z=315.50], EntityItemLoot['item.item.string'/37673, l='MpServer', x=-182.24, y=25.00, z=298.39], EntityToad['Toad'/29497, l='MpServer', x=-254.50, y=71.00, z=243.50], EntityToad['Toad'/29498, l='MpServer', x=-254.50, y=71.00, z=242.50], EntityCreeper['Creeper'/39739, l='MpServer', x=-222.50, y=52.00, z=336.50], EntityToad['Toad'/29499, l='MpServer', x=-243.24, y=68.00, z=258.89], EntityToad['Toad'/29500, l='MpServer', x=-250.50, y=68.00, z=257.50], EntitySkeleton['Skeleton'/39756, l='MpServer', x=-201.50, y=17.00, z=351.50], MoCEntityWerewolf['Werewolf'/37755, l='MpServer', x=-208.16, y=55.00, z=314.48], EntityTroll['Troll'/39814, l='MpServer', x=-140.50, y=17.00, z=283.50], EntityToad['Toad'/29608, l='MpServer', x=-241.50, y=68.00, z=256.50], EntityToad['Toad'/29609, l='MpServer', x=-241.50, y=68.00, z=258.50], MoCEntityPanther['Panther'/29610, l='MpServer', x=-232.01, y=67.00, z=247.05], MoCEntityPanther['Panther'/29611, l='MpServer', x=-241.98, y=67.00, z=240.03], MoCEntityBlackBear['BlackBear'/29612, l='MpServer', x=-243.40, y=70.00, z=266.27], MoCEntityBlackBear['BlackBear'/29613, l='MpServer', x=-241.33, y=70.00, z=266.25], MoCEntityBlackBear['BlackBear'/29614, l='MpServer', x=-246.10, y=68.00, z=261.06], MoCEntitySnake['Snake'/29615, l='MpServer', x=-240.96, y=74.00, z=292.00], MoCEntitySnake['Snake'/29616, l='MpServer', x=-225.00, y=70.00, z=293.03], EntityCreeper['Creeper'/39859, l='MpServer', x=-255.50, y=12.00, z=281.50], MoCEntityBunny['Bunny'/29624, l='MpServer', x=-234.50, y=91.00, z=317.50], MoCEntitySnake['Snake'/29640, l='MpServer', x=-235.50, y=97.00, z=328.50], MoCEntitySnake['Snake'/29642, l='MpServer', x=-246.50, y=101.00, z=333.50], EntityIceDragon['Ice Dragon'/29643, l='MpServer', x=-246.40, y=103.00, z=329.60], EntityZombie['Zombie'/39889, l='MpServer', x=-134.50, y=63.00, z=240.50], EntityItemLoot['item.item.iceandfire.troll_tusk'/39896, l='MpServer', x=-161.13, y=17.00, z=362.29], EntityItemLoot['item.item.iceandfire.troll_leather_forest'/39897, l='MpServer', x=-162.43, y=17.00, z=361.15], EntityItemLoot['item.tile.stonebricksmooth.mossy'/39974, l='MpServer', x=-161.13, y=17.00, z=361.99], EntityToad['Toad'/29736, l='MpServer', x=-224.50, y=68.00, z=253.07], EntityItemLoot['item.tile.stonebricksmooth.cracked'/39976, l='MpServer', x=-161.21, y=17.00, z=361.88], EntityEweFriesian['Friesian Ewe'/29741, l='MpServer', x=-226.01, y=80.00, z=322.75], EntityRamFriesian['Friesian Ram'/29745, l='MpServer', x=-224.50, y=78.00, z=325.50], MoCEntityBunny['Bunny'/29746, l='MpServer', x=-222.50, y=87.00, z=334.50], MoCEntityBunny['Bunny'/29747, l='MpServer', x=-225.50, y=86.00, z=333.50], MoCEntityAngler['Angler'/40014, l='MpServer', x=-167.35, y=62.00, z=372.30], MoCEntityAngler['Angler'/40015, l='MpServer', x=-171.85, y=61.02, z=367.69], MoCEntityAngler['Angler'/40016, l='MpServer', x=-163.99, y=61.00, z=372.11], EntityItemLoot['item.tile.gravel'/33882, l='MpServer', x=-165.98, y=23.00, z=339.23], EntitySkeleton['Skeleton'/40028, l='MpServer', x=-221.50, y=14.00, z=352.50], EntityItemLoot['item.item.feather'/33907, l='MpServer', x=-181.13, y=62.91, z=342.17], EntityItemLoot['item.item.iceandfire.troll_tusk'/38037, l='MpServer', x=-191.21, y=24.00, z=310.13], EntityItemLoot['item.item.iceandfire.troll_leather_forest'/38038, l='MpServer', x=-191.37, y=24.00, z=310.13], EntityItemLoot['item.tile.flower1.dandelion'/35992, l='MpServer', x=-144.87, y=68.00, z=272.88], EntitySowLargeWhite['Large White Sow'/29853, l='MpServer', x=-189.86, y=68.00, z=268.83], EntityHogLargeWhite['Large White Hog'/29854, l='MpServer', x=-228.18, y=68.00, z=259.85], EntitySpider['Spider'/38046, l='MpServer', x=-148.50, y=29.00, z=358.50], EntityPigletLargeWhite['Large White Piglet'/29855, l='MpServer', x=-185.54, y=68.00, z=275.33], EntityHogLargeWhite['Large White Hog'/29858, l='MpServer', x=-217.14, y=69.00, z=286.22], EntityPigletLargeWhite['Large White Piglet'/29859, l='MpServer', x=-214.38, y=76.00, z=316.33], EntityItemLoot['item.item.iceandfire.troll_weapon.hammer'/38057, l='MpServer', x=-191.13, y=24.00, z=310.81], MoCEntitySnake['Snake'/29865, l='MpServer', x=-203.09, y=102.00, z=377.13], EntityAshen['Ashen'/38087, l='MpServer', x=-189.50, y=14.00, z=333.50], EntitySlime['Slime'/40144, l='MpServer', x=-171.22, y=27.00, z=366.74], EntityItemLoot['item.item.arrow'/40152, l='MpServer', x=-247.23, y=81.00, z=282.66], EntityItemLoot['item.item.bone'/40153, l='MpServer', x=-248.18, y=82.00, z=281.34], EntityGib['unknown'/40158, l='MpServer', x=-249.25, y=79.00, z=280.75], EntityGib['unknown'/40159, l='MpServer', x=-249.74, y=79.00, z=280.85], EntityGib['unknown'/40160, l='MpServer', x=-249.47, y=79.00, z=280.15], EntityGib['unknown'/40161, l='MpServer', x=-249.75, y=79.00, z=280.75], EntityGib['unknown'/40162, l='MpServer', x=-249.15, y=78.00, z=280.16], EntityGib['unknown'/40163, l='MpServer', x=-249.85, y=78.00, z=280.48], EntityItemLoot['item.item.feather'/40165, l='MpServer', x=-157.06, y=72.00, z=351.83], EntitySkeleton['Skeleton'/40176, l='MpServer', x=-167.50, y=16.00, z=333.50], EntitySkeleton['Skeleton'/38143, l='MpServer', x=-237.50, y=35.00, z=280.50], EntityItemLoot['item.tile.gravel'/34048, l='MpServer', x=-166.88, y=23.00, z=340.36], EntityZombie['Zombie'/40199, l='MpServer', x=-139.50, y=42.00, z=265.50], EntitySkeleton['Skeleton'/38153, l='MpServer', x=-136.50, y=71.00, z=272.31], EntityItemLoot['item.tile.flower2.oxeyeDaisy'/38159, l='MpServer', x=-162.01, y=100.00, z=317.81], EntityItemLoot['item.tile.mushroom13'/29969, l='MpServer', x=-193.50, y=17.00, z=342.84], EntityCreeper['Creeper'/40215, l='MpServer', x=-134.50, y=82.00, z=309.50], EntityCreeper['Creeper'/40243, l='MpServer', x=-167.50, y=17.00, z=267.50], EntitySkeleton['Skeleton'/40267, l='MpServer', x=-153.50, y=25.00, z=348.50], EntityItemLoot['item.item.feather'/38239, l='MpServer', x=-150.51, y=79.00, z=364.42], EntityItemLoot['item.tile.mushroom'/36202, l='MpServer', x=-159.81, y=18.00, z=308.74], EntityItemLoot['item.item.iceandfire.troll_leather_forest'/36203, l='MpServer', x=-159.07, y=18.00, z=308.44], EntityItemLoot['item.item.string'/40299, l='MpServer', x=-221.38, y=14.00, z=351.13], EntityItemLoot['item.item.stick'/36210, l='MpServer', x=-159.53, y=18.00, z=308.82], EntityItemLoot['item.tile.stonebrick'/36212, l='MpServer', x=-159.72, y=18.00, z=308.34], EntitySkeleton['Skeleton'/40308, l='MpServer', x=-200.50, y=17.00, z=355.50], MoCEntityBunny['Bunny'/30088, l='MpServer', x=-182.44, y=85.00, z=224.21], MoCEntityMouse['Mouse'/30089, l='MpServer', x=-178.54, y=66.00, z=245.66], MoCEntityBunny['Bunny'/30093, l='MpServer', x=-172.50, y=67.00, z=246.81], MoCEntityBunny['Bunny'/30094, l='MpServer', x=-173.35, y=72.00, z=240.51], MoCEntityBunny['Bunny'/30097, l='MpServer', x=-183.36, y=66.00, z=246.50], EntityHenLeghorn['Leghorn Hen'/30099, l='MpServer', x=-157.50, y=72.00, z=352.31], EntityRoosterLeghorn['Leghorn Rooster'/30101, l='MpServer', x=-181.52, y=63.00, z=339.48], EntityLatchedRenderer['unknown'/40341, l='MpServer', x=-199.72, y=70.00, z=301.02], EntityZombie['Zombie'/40347, l='MpServer', x=-149.50, y=22.23, z=356.77], EntityZombie['Zombie'/40364, l='MpServer', x=-139.50, y=18.00, z=314.50], EntityItemLoot['item.tile.mushroom'/40368, l='MpServer', x=-157.69, y=28.00, z=355.04], EntityHenRhodeIslandRed['Rhode Island Red Hen'/30137, l='MpServer', x=-180.48, y=70.00, z=293.77], EntityRoosterRhodeIslandRed['Rhode Island Red Rooster'/30143, l='MpServer', x=-161.50, y=91.00, z=293.50], EntitySkeleton['Skeleton'/38337, l='MpServer', x=-208.50, y=17.00, z=353.50], MoCEntityEnt['Ent'/30148, l='MpServer', x=-165.50, y=93.00, z=327.50], EntityHenWyandotte['Wyandotte Hen'/30155, l='MpServer', x=-174.27, y=80.00, z=331.52], EntityRoosterWyandotte['Wyandotte Rooster'/30156, l='MpServer', x=-140.50, y=90.00, z=345.76], EntityChickWyandotte['Wyandotte Chick'/30157, l='MpServer', x=-161.37, y=70.00, z=349.26], EntityItemLoot['item.tile.log.oak'/40401, l='MpServer', x=-157.35, y=28.22, z=354.49], EntityItemLoot['item.tile.log.oak'/40403, l='MpServer', x=-157.51, y=28.22, z=354.67], EntityItemLoot['item.item.emerald'/38359, l='MpServer', x=-165.90, y=29.00, z=304.88], EntityItemLoot['item.item.iceandfire.troll_tusk'/38364, l='MpServer', x=-168.12, y=32.00, z=309.24], EntityItemLoot['item.item.iceandfire.troll_leather_forest'/38365, l='MpServer', x=-168.28, y=31.00, z=310.73], EntityItemLoot['item.item.bone'/38380, l='MpServer', x=-166.91, y=32.00, z=307.28], EntityItemLoot['item.tile.stonebrick'/38382, l='MpServer', x=-168.88, y=32.00, z=307.44], EntityItemLoot['item.item.iceandfire.troll_weapon.column_forest'/38384, l='MpServer', x=-167.80, y=32.00, z=310.42], MoCEntityDuck['Duck'/30197, l='MpServer', x=-140.44, y=97.00, z=238.60], MoCEntityDuck['Duck'/30198, l='MpServer', x=-138.50, y=97.00, z=242.50], EntityItemLoot['item.tile.mushroom13'/30200, l='MpServer', x=-153.85, y=28.00, z=255.60], MoCEntityEnt['Ent'/30201, l='MpServer', x=-145.48, y=66.00, z=265.75], MoCEntityEnt['Ent'/30202, l='MpServer', x=-142.36, y=69.00, z=272.66], MoCEntityBird['Bird'/30203, l='MpServer', x=-170.55, y=67.21, z=281.26], MoCEntityBird['Bird'/30204, l='MpServer', x=-146.77, y=53.30, z=257.34], MoCEntityBird['Bird'/30205, l='MpServer', x=-151.34, y=28.00, z=261.80], MoCEntityGrizzlyBear['GrizzlyBear'/30206, l='MpServer', x=-144.74, y=98.00, z=308.94], MoCEntityGrizzlyBear['GrizzlyBear'/30207, l='MpServer', x=-146.09, y=98.00, z=310.09], EntityHenWyandotte['Wyandotte Hen'/30211, l='MpServer', x=-158.81, y=100.00, z=310.77], EntityRoosterWyandotte['Wyandotte Rooster'/30212, l='MpServer', x=-149.00, y=98.00, z=320.98], EntityCreeper['Creeper'/38450, l='MpServer', x=-141.50, y=31.00, z=302.50], MoCEntityDuck['Duck'/30270, l='MpServer', x=-134.50, y=96.00, z=296.50], MoCEntityDuck['Duck'/30271, l='MpServer', x=-135.50, y=97.00, z=297.50], MoCEntityRaccoon['Raccoon'/30272, l='MpServer', x=-121.50, y=98.00, z=334.50], EntityCreeper['Creeper'/38471, l='MpServer', x=-220.50, y=53.00, z=297.50], EntityCreeper['Creeper'/36447, l='MpServer', x=-166.50, y=26.00, z=309.50], MoCEntityFirefly['Firefly'/34438, l='MpServer', x=-181.44, y=38.00, z=262.51], EntityItemLoot['item.item.minecraft:porkchop'/36503, l='MpServer', x=-208.30, y=72.00, z=310.36], EntityItemLoot['item.item.quark:tallow'/36504, l='MpServer', x=-208.13, y=72.00, z=311.64], MoCEntityDragonfly['DragonFly'/34468, l='MpServer', x=-150.30, y=76.00, z=350.62], EntityItemLoot['item.tile.flower_1.miners_delight'/34495, l='MpServer', x=-256.11, y=12.00, z=275.15], EntityItemLoot['item.item.animania_raw_frog_legs'/34508, l='MpServer', x=-157.61, y=68.00, z=275.12], EntityItemLoot['item.item.leather'/34515, l='MpServer', x=-223.66, y=92.00, z=338.56], EntityItemLoot['item.item.minecraft:beef'/34516, l='MpServer', x=-223.80, y=92.00, z=338.88], EntityItemLoot['item.tile.flower2.tulipRed'/32471, l='MpServer', x=-158.88, y=71.00, z=247.97], EntityItemLoot['item.item.leather'/34519, l='MpServer', x=-225.85, y=95.00, z=339.88], EntityItemLoot['item.item.minecraft:beef'/34520, l='MpServer', x=-226.68, y=95.00, z=338.94], EntityItemLoot['item.item.string'/34522, l='MpServer', x=-157.88, y=25.00, z=346.08], EntitySpider['Spider'/38647, l='MpServer', x=-216.50, y=47.00, z=272.50], MoCEntityFly['Fly'/34670, l='MpServer', x=-232.77, y=69.00, z=273.51], MoCEntityFly['Fly'/34671, l='MpServer', x=-220.23, y=69.00, z=287.48], MoCEntityFly['Fly'/34672, l='MpServer', x=-237.56, y=71.00, z=302.60], MoCEntityBee['Bee'/34673, l='MpServer', x=-228.51, y=70.00, z=288.54], MoCEntityFirefly['Firefly'/34674, l='MpServer', x=-209.13, y=67.00, z=221.30], MoCEntityFly['Fly'/34677, l='MpServer', x=-248.96, y=68.00, z=255.83], MoCEntityAnchovy['Anchovy'/34720, l='MpServer', x=-178.51, y=62.00, z=357.85], MoCEntityAnchovy['Anchovy'/34721, l='MpServer', x=-173.15, y=61.99, z=350.99], MoCEntityAnchovy['Anchovy'/34722, l='MpServer', x=-178.57, y=61.00, z=343.15], MoCEntityBass['Bass'/34723, l='MpServer', x=-175.50, y=60.40, z=360.50], EntityItemLoot['item.item.animania_raw_frog_legs'/36785, l='MpServer', x=-157.15, y=79.00, z=336.13], EntityItemLoot['item.item.string'/36829, l='MpServer', x=-215.68, y=52.00, z=336.24]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/31358, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 987762816 bytes (942 MB) / 10017046528 bytes (9553 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.5.2784 284 mods loaded, 284 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

**Comment by asiekierka** [comment]
Well, an API broke

**Comment by sa13103** [comment]
are you able to discern which one? is there something i can attempt on my end to correct it? forgive me im not good at all at reading coding. :/

**Comment by asiekierka** [comment]
Do you have the latest version of CTM, Chisel, etc.?
